/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Import Montserrat font from Google Fonts
import "./globals.css";

// Load Montserrat font using next/font/google
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"], // Add all the font weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Include the Montserrat font link for wider browser compatibility */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;700&display=swap"
        />
      </head>
      <body
        className={`${montserrat.variable} antialiased`} // Apply the font globally using Tailwind's `font-sans`
      >
        {children}
      </body>
    </html>
  );
}
